import type { StoryChapterDefinition } from "../types";

export const CHAPTER_TWO: StoryChapterDefinition = {
  id: "chapter-02-three-geometries",
  order: 2,
  numeral: "II",
  publication: { state: "PUBLISHED", label: "АВТОРСКИЙ КАНОН" },
  title: "Три геометрии ответа",
  subtitle: "Один импульс — три честных способа встретить его",
  menu: {
    eyebrow: "ВОРОН-МАГ · ЖИВОЙ МИР · НЕИЗБЕЖНЫЙ ОСТАТОК",
    titleLines: ["ВСТРЕТЬ", "ИМПУЛЬС"],
    synopsis: "Волшебник испытывает новую форму Ворона. Чтобы сохранить обе жизни, придётся освоить Бросок, Якорь и Разлом — не меняя силы самой Природы.",
    formula: "I = absorbed(method,π) + residual(method,π)",
  },
  runtime: {
    id: "WORLD_JOURNEY_V2",
    start: "RESET_WORLD",
    progressLabel: "ГЕОМЕТРИИ",
  },
  openingSceneId: "scene-00-one-impulse",
  scenes: [
    {
      id: "scene-00-one-impulse",
      kind: "OPENING",
      indexLabel: "СЦЕНА 00",
      title: "ОДИН ИМПУЛЬС",
      fieldLabel: "СУММА СОХРАНЕНА",
      boundary: "Σv′ = Σv · residual > 0",
      boundaryLabel: "ЗАКОН ЖИВОГО МИРА",
      left: {
        asset: "/hero-crow-v2.webp",
        alt: "Ворон-маг перед испытанием трёх геометрий",
        eyebrow: "FORM II / WORLD MAGUS",
        name: "ВОРОН-МАГ",
      },
      right: {
        asset: "/emerald-wizard-portrait-v2.webp",
        alt: "Удалённая изумрудная проекция Волшебника",
        eyebrow: "REMOTE PROJECTION",
        name: "ВОЛШЕБНИК",
      },
      beats: [
        {
          speaker: "ВОЛШЕБНИК",
          state: "ОТВЕТСТВЕННОСТЬ",
          line: "Ты называешь себя магом потому, что увидел, из чего сделан Мир?",
          responseSpeaker: "ВОРОН",
          response: "Нет. Потому что теперь отвечаю за то, что в нём изменяю.",
          cue: "PROLOGUE_FIELD",
        },
        {
          speaker: "ВОЛШЕБНИК",
          state: "НЕВОЗМОЖНОЕ НЕПРОБИТИЕ",
          line: "Природу нельзя остановить. Любая твоя форма будет пробита.",
          responseSpeaker: "ВОРОН",
          response: "Но один и тот же импульс можно встретить по-разному.",
          cue: "CURSE_PULSE",
        },
        {
          speaker: "ВОЛШЕБНИК",
          state: "ТРИ ГЕОМЕТРИИ",
          line: "Бросок откроет оси. Якорь выровняет поток. Разлом потребует выбрать плоскость вслепую.",
          responseSpeaker: "ВОРОН",
          response: "Три геометрии. Один долг перед живым Миром.",
          cue: "SPELL_SEAL",
        },
        {
          speaker: "ВОЛШЕБНИК",
          state: "ЧЕСТНЫЙ СЛЕД",
          line: "Ошибись — и Мир запомнит цену.",
          responseSpeaker: "ВОРОН",
          response: "Пусть Срез покажет всё. Я не стану прятать ошибку.",
          cue: "WORLD_GATE",
        },
      ],
      exitLabel: "ВСТРЕТИТЬ ИМПУЛЬС →",
    },
  ],
  finale: {
    trigger: "DEFENSE_MASTERY_BALANCE",
    exit: "CHAPTER_MENU",
    header: "ГЛАВА II / ФИНАЛ",
    protocol: "СЕРТИФИКАТ БАЛАНСА",
    left: {
      asset: "/hero-crow-v2.webp",
      alt: "Ворон — хранитель баланса живого Мира",
      eyebrow: "KEEPER OF BALANCE",
      name: "ВОРОН-МАГ",
    },
    right: {
      asset: "/emerald-wizard-portrait-v2.webp",
      alt: "Изумрудная проекция Волшебника даёт трещину",
      eyebrow: "PROJECTION / FRACTURE",
      name: "ВОЛШЕБНИК",
    },
    contactLabel: "НУЛЕВОЙ ЩИТ",
    contactFormula: "THROW ∧ ANCHOR ∧ RIFT ∧ balance ≥ 65",
    kicker: "ЛОЖНАЯ ЧЕТВЁРТАЯ ГЕОМЕТРИЯ",
    title: "НУЛЕВОЙ ЩИТ",
    bodyFallback: "Волшебник предложил защиту без остатка. Ворон увидел в ней не всемогущество, а спрятанную цену.",
    theorem: "I = absorbed + residual ∧ residual > 0",
    consequence: "ВОРОН НЕ СТАЛ ВСЕМОГУЩИМ. ОН СТАЛ ХРАНИТЕЛЕМ БАЛАНСА.",
    acceptLabel: "ЗАВЕРШИТЬ ГЛАВУ II →",
    beats: [
      {
        speaker: "ВОЛШЕБНИК",
        state: "ИСКУШЕНИЕ",
        line: "Ты испытал три формы. Теперь выбери четвёртую — ту, которая не пропускает ничего.",
        responseSpeaker: "ВОРОН",
        response: "Такой формы нет. Нулевой остаток означает, что ты спрятал цену.",
        cue: "CURSE_PULSE",
      },
      {
        speaker: "ВОЛШЕБНИК",
        state: "ВЛАСТЬ",
        line: "Настоящий маг переписывает закон.",
        responseSpeaker: "ВОРОН",
        response: "Настоящий маг видит закон, выбирает цену и отвечает за последствия.",
        cue: "SPELL_SEAL",
      },
      {
        speaker: "ВОЛШЕБНИК",
        state: "СВИДЕТЕЛЬСТВО",
        line: "Тогда покажи, что осталось после твоей защиты.",
        responseSpeaker: "ВОРОН",
        response: "Живой Ворон. Живой Мир. И полный след между ними.",
        cue: "PROLOGUE_FIELD",
      },
      {
        speaker: "ВОЛШЕБНИК",
        state: "ТРЕЩИНА",
        line: "Ты отказался от всемогущества.",
        responseSpeaker: "ВОРОН",
        response: "Я отказался от лжи о нём.",
        cue: "WORLD_GATE",
      },
    ],
  },
};
