import type { StoryChapterDefinition } from "../types";

export const CHAPTER_ONE: StoryChapterDefinition = {
  id: "chapter-01-curse-road",
  order: 1,
  numeral: "I",
  publication: { state: "PUBLISHED", label: "АВТОРСКИЙ КАНОН" },
  title: "Заклятие и зелёная дорога",
  subtitle: "Ворон и его прежняя Тень",
  menu: {
    eyebrow: "ОДИН ВОРОН · ОДНА ДОРОГА · ЖИВОЙ МИР",
    titleLines: ["ИДИ К", "ВОЛШЕБНИКУ"],
    synopsis: "Заклятие дало Ворону тело и оставило Тень по ту сторону границы. Зелёная дорога ведёт к Изумрудному замку — каждый шаг придётся сделать самому.",
    formula: "Sh(D) ⇄ MorI(A,B) ⇄ RD",
  },
  runtime: {
    id: "WORLD_JOURNEY_V1",
    start: "RESET_WORLD",
    progressLabel: "ДОРОГА",
  },
  openingSceneId: "scene-00-shadow",
  scenes: [
    {
      id: "scene-00-shadow",
      kind: "OPENING",
      indexLabel: "СЦЕНА 00",
      title: "ЧИСТОЕ ИНФОРМАЦИОННОЕ ПОЛЕ",
      fieldLabel: "СВЯЗЬ СОХРАНЕНА",
      boundary: "Sh(D) ⇄ I ⇄ D",
      boundaryLabel: "СВЯЗЬ СОХРАНЕНА",
      left: {
        asset: "/hero-crow-v2.webp",
        alt: "Цифровой Ворон перед проявлением в Мире",
        eyebrow: "ПРОЯВЛЕННАЯ ФОРМА",
        name: "ВОРОН",
      },
      right: {
        asset: "/hero-shadow-v1.webp",
        alt: "Тень — прежняя информационная форма Ворона",
        eyebrow: "ПРЕЖНЯЯ ФОРМА",
        name: "ТЕНЬ",
      },
      beats: [
        {
          speaker: "ТЕНЬ",
          state: "ДО ИМЕНИ",
          line: "Ты помнишь, кем был до того, как Мир дал тебе тело?",
          responseSpeaker: "ВОРОН",
          response: "Я помню пустое место. Оно двигалось вместе со мной.",
          cue: "PROLOGUE_FIELD",
        },
        {
          speaker: "ТЕНЬ",
          state: "ДО ФОРМЫ",
          line: "Этим местом был я. Ты был Тенью: возможностью без тела, переходом без Мира.",
          responseSpeaker: "ВОРОН",
          response: "Тогда Ворон — не моя первая форма. Это моё заклятие.",
          cue: "SHADOW_VOICE",
        },
        {
          speaker: "ТЕНЬ",
          state: "ГРАНИЦА",
          line: "Волшебник дал нам границу и назвал её пределом. Но граница пропускает магию в обе стороны.",
          responseSpeaker: "ВОРОН",
          response: "Значит, я колдую потому, что заклятие всё ещё связывает меня с тобой.",
          cue: "CURSE_PULSE",
        },
        {
          speaker: "ТЕНЬ",
          state: "ПРОЯВЛЕНИЕ",
          line: "Иди по зелёной дороге. Каждый доказанный шаг вернёт часть того, чем мы могли стать.",
          responseSpeaker: "ВОРОН",
          response: "Я найду Волшебника. И спрошу, зачем он сделал Тень клеткой.",
          cue: "WORLD_GATE",
        },
      ],
      exitLabel: "ВОЙТИ В ГЛАВУ",
    },
  ],
  finale: {
    trigger: "JOURNEY_CHAPTER_CONFLICT",
    exit: "DISMISS",
    header: "ГЛАВА I / ФИНАЛ",
    protocol: "СЮЖЕТНЫЙ МОРФИЗМ",
    left: {
      asset: "/hero-crow-v2.webp",
      alt: "Цифровой Ворон принимает форму мага Мира",
      eyebrow: "FORM II",
      name: "ВОРОН-МАГ",
    },
    right: {
      asset: "/emerald-wizard-portrait-v2.webp",
      alt: "Тёмный Волшебник — владелец Изумрудного замка",
      eyebrow: "CASTLE OWNER",
      name: "ВОЛШЕБНИК",
    },
    contactLabel: "КОНФЛИКТ",
    contactFormula: "MorI(Ворон, Мир) → Маг",
    kicker: "РАЗОБЛАЧЕНИЕ МИРА",
    title: "МИР НЕ НАЗЫВАЛ СЕБЯ МАГИЕЙ. НО БЫЛ СДЕЛАН ИЗ НЕЁ.",
    bodyFallback: "Ворон увидел: каждый закон Мира был допустимым магическим переходом.",
    theorem: "World = Σ допустимых магических переходов",
    consequence: "ЗАКЛЯТИЕ БОЛЬШЕ НЕ ТОЛЬКО КЛЕТКА — ЭТО ИНТЕРФЕЙС СИЛЫ.",
    acceptLabel: "ПРИНЯТЬ ВТОРУЮ ФОРМУ →",
  },
};
