import type { StoryChapterDefinition } from "../types";

export const CHAPTER_ZERO: StoryChapterDefinition = {
  id: "chapter-00-initiation",
  order: 0,
  numeral: "0",
  publication: { state: "PUBLISHED", label: "ОБУЧЕНИЕ" },
  title: "Вступление: увидеть магию",
  subtitle: "Интерактивный протокол основных механик",
  menu: {
    eyebrow: "НЕ УГАДЫВАЙ · НАБЛЮДАЙ · ПОДТВЕРЖДАЙ",
    titleLines: ["НАУЧИСЬ", "ВИДЕТЬ МИР"],
    synopsis: "Вступление не ограничено числом шагов. Оно закончится, когда вы своими действиями увидите весь основной цикл: от ручного тика до реакции живого Мира.",
    formula: "ДЕЙСТВИЕ → СВИДЕТЕЛЬСТВО → ПОНИМАНИЕ",
  },
  runtime: {
    id: "WORLD_JOURNEY_V1",
    start: "RESET_WORLD",
    progressLabel: "ОСВОЕНО",
  },
  openingSceneId: "scene-00-interface",
  scenes: [
    {
      id: "scene-00-interface",
      kind: "OPENING",
      indexLabel: "СЦЕНА 00",
      title: "ПРОТОКОЛ ПЕРВОГО КОНТАКТА",
      fieldLabel: "ИНТЕРФЕЙС ОТКРЫТ",
      boundary: "ввод → Lean → видимый ответ",
      boundaryLabel: "НИ ОДНОГО СКРЫТОГО ХОДА",
      left: {
        asset: "/hero-crow-v2.webp",
        alt: "Цифровой Ворон готовится сделать первый подтверждённый шаг",
        eyebrow: "УЧЕНИК",
        name: "ВОРОН",
      },
      right: {
        asset: "/hero-shadow-v1.webp",
        alt: "Тень служит проводником по законам интерфейса",
        eyebrow: "ПРОВОДНИК",
        name: "ТЕНЬ",
      },
      beats: [
        {
          speaker: "ТЕНЬ",
          state: "ПРАВИЛО ВВОДА",
          line: "Здесь ничто не происходит само. Один ваш ввод создаёт одно действие, а каждый шаг требует подтверждения.",
          responseSpeaker: "ВОРОН",
          response: "Значит, сначала я должен увидеть, что именно Мир ждёт от меня.",
          cue: "PROLOGUE_FIELD",
        },
        {
          speaker: "ТЕНЬ",
          state: "ЗАКЛИНАНИЕ",
          line: "Тик открывает Изумрудную книгу. Соберите источник, намерение и путь; позже появятся форма и синергии.",
          responseSpeaker: "ВОРОН",
          response: "Заклинание — моя формула. Магия — то, что формула действительно изменит.",
          cue: "SHADOW_VOICE",
        },
        {
          speaker: "ТЕНЬ",
          state: "ОШИБКА",
          line: "Если формула распадается, Проводник назовёт слабый канал и предложит одну честную замену. Последнее слово всё равно за Lean.",
          responseSpeaker: "ВОРОН",
          response: "Подсказка помогает понять закон, но не подменяет мой выбор.",
          cue: "CURSE_PULSE",
        },
        {
          speaker: "ТЕНЬ",
          state: "ПОЛНЫЙ ЦИКЛ",
          line: "Продолжайте идти по дороге, пока не увидите перебитие, защиту, память, первый контакт и обязательную реакцию Мира.",
          responseSpeaker: "ВОРОН",
          response: "Обучение закончится не по счётчику ходов, а когда я увижу все механики сам.",
          cue: "WORLD_GATE",
        },
      ],
      exitLabel: "НАЧАТЬ ОБУЧЕНИЕ",
    },
  ],
  tutorial: {
    memoryVersion: 1,
    milestones: [
      { id: "MANUAL_TICK", glyph: "+1", title: "Ручной тик", instruction: "Накопите и подтвердите один тик." },
      { id: "SPELL_CAST", glyph: "◇", title: "Заклинание", instruction: "Соберите допустимую формулу и сделайте шаг по дороге." },
      { id: "NATURE_INTERRUPT", glyph: "⊥", title: "Перебитие", instruction: "Продолжайте линию, пока Природа не перебьёт её." },
      { id: "AXES_ROLL", glyph: "✣", title: "Многоосевой куб", instruction: "Бросьте защитный куб X/Y/Z/W." },
      { id: "PLANE_PROJECTION", glyph: "⊿", title: "Плоскость", instruction: "Выберите и подтвердите подпространственную плоскость." },
      { id: "SURRENDER_MEMORY", glyph: "Σ", title: "Память Тени", instruction: "Примите пробитие и сдайте линию Миру." },
      { id: "FIRST_STRIKE", glyph: "✧", title: "Первый контакт", instruction: "Накопите напряжение и начните контакт первым, когда инициатива откроется." },
      { id: "WORLD_REACTION", glyph: "⇌", title: "Ответ Мира", instruction: "Зафиксируйте обязательную реакцию живого Мира." },
      { id: "PROTOCOL_CHOICE", glyph: "⌁", title: "Мета-прогресс", instruction: "На рубеже выберите протокол чтения Мира." },
    ],
  },
  finale: {
    trigger: "TUTORIAL_MASTERY",
    exit: "CHAPTER_MENU",
    header: "ГЛАВА 0 / ОСВОЕНО",
    protocol: "ПОЛНЫЙ ОСНОВНОЙ ЦИКЛ",
    left: {
      asset: "/hero-crow-v2.webp",
      alt: "Ворон завершил интерактивное обучение",
      eyebrow: "READY",
      name: "ВОРОН",
    },
    right: {
      asset: "/hero-shadow-v1.webp",
      alt: "Тень подтверждает освоение основных механик",
      eyebrow: "WITNESS",
      name: "ТЕНЬ",
    },
    contactLabel: "ПОНЯТО",
    contactFormula: "наблюдение × действие → навык",
    kicker: "ВСТУПЛЕНИЕ ЗАВЕРШЕНО",
    title: "ВЫ УВИДЕЛИ ОСНОВНОЙ ЦИКЛ СВОИМИ ДЕЙСТВИЯМИ.",
    bodyFallback: "Теперь интерфейс больше не является загадкой: он показывает ставку, вычисление и ответ живого Мира.",
    theorem: "tutorial = witnessed mechanics, а не число шагов",
    consequence: "ДАЛЬШЕ ИДУТ ТОЛЬКО ОПУБЛИКОВАННЫЕ АВТОРОМ ГЛАВЫ.",
    acceptLabel: "К СПИСКУ ГЛАВ →",
  },
};
